# Reads .env and writes js/config.js for local dev.
# Usage: .\generate-config.ps1
# To reset to offline mode: git checkout js/config.js

$envFile = ".env"
if (-not (Test-Path $envFile)) {
    Write-Error ".env not found. Copy .env.example to .env and fill in your values."
    exit 1
}

$vars = @{}
foreach ($line in (Get-Content $envFile)) {
    if ($line -match "^\s*([^#][^=]+)=(.*)$") {
        $vars[$matches[1].Trim()] = $matches[2].Trim()
    }
}

$required = @("SUPABASE_URL", "SUPABASE_ANON_KEY", "APP_TOKEN")
foreach ($key in $required) {
    if (-not $vars.ContainsKey($key)) {
        Write-Error "Missing $key in .env"
        exit 1
    }
}

$config = @"
// Local dev config — generated by generate-config.ps1. Do not commit with real values.
window.APP_CONFIG = {
    supabaseUrl: "$($vars['SUPABASE_URL'])",
    supabaseKey: "$($vars['SUPABASE_ANON_KEY'])",
    appToken:    "$($vars['APP_TOKEN'])"
};
"@

$config | Out-File -FilePath "js\config.js" -Encoding utf8 -NoNewline
Write-Host "js/config.js written. Run 'git checkout js/config.js' to reset to offline mode."
